name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm i

    - name: Build
      run: npx -p @skyux-sdk/cli skyux build

    - name: Single Page Application Hack
      run: cp dist/index.html dist/404.html

    - name: Publish
      uses: crazy-max/ghaction-github-pages@v1
      if: success()
      with:
        keep_history: true
        build_dir: dist
        commit_message: "Build for ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TO_PROD }}
