name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd hello-world
        npx -p @angular/cli ng build --prod
        cp dist/hello-world/index.html dist/hello-world/404.html
        cd ../
        
    - name: Publish
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git add .
        git commit -am "Build for ${GITHUB_SHA}"
        git subtree push --prefix hello-world/dist/hello-world origin gh-pages
        git push origin gh-pages -f
