name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Publish
      run: |
        cd dist/
        cp index.html 404.html
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git switch -c gh-pages
        git add .
        git commit -am "Build for ${GITHUB_SHA}"
        git push origin gh-pages -f
