name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash

    - name: Build
      run: |
        cd hello-world
        npm i
        npx -p @angular/cli ng build --prod --output-path dist --base-href /$REPOSITORY_NAME/
        cp dist/index.html dist/404.html
        cd ../
        
    - name: Publish
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git add .
        git commit -am "Build for ${GITHUB_SHA}"
        git subtree split --prefix hello-world/dist -b gh-pages
        git push -f origin gh-pages:gh-pages
