name: Test and Build

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i

  test:
    name: SKYUX Test
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - run: npx -p @skyux-sdk/cli skyux test --headless

  build:
    name: SKYUX Build
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - run: npx -p @skyux-sdk/cli skyux build
